// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropManageX.Models.Context;

#nullable disable

namespace PropManageX.Migrations
{
    [DbContext(typeof(PropManageXContext))]
    [Migration("20260312051247_Int")]
    partial class Int
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropManageX.Models.Entities.AmenityModel", b =>
                {
                    b.Property<int>("AmenityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenityID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.HasKey("AmenityID");

                    b.HasIndex("PropertyID");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.ContractModel", b =>
                {
                    b.Property<int>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractID"));

                    b.Property<string>("ContractType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ContractValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DealID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContractID");

                    b.HasIndex("DealID");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.DealModel", b =>
                {
                    b.Property<int>("DealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DealID"));

                    b.Property<decimal>("AgreedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpectedClosureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeadID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("DealID");

                    b.HasIndex("LeadID");

                    b.HasIndex("UnitID");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.DocumentModel", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityID")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentID");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.InvoiceModel", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ContractID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Period")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvoiceID");

                    b.HasIndex("ContractID");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.LeadModel", b =>
                {
                    b.Property<int>("LeadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadID"));

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PropertyID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeadID");

                    b.HasIndex("PropertyID");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.MaintenanceRequestModel", b =>
                {
                    b.Property<int>("RequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RaisedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TenantID")
                        .HasColumnType("int");

                    b.Property<int?>("UnitID")
                        .HasColumnType("int");

                    b.HasKey("RequestID");

                    b.HasIndex("TenantID");

                    b.HasIndex("UnitID");

                    b.ToTable("MaintenanceRequests");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.NotificationModel", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.PropertyModel", b =>
                {
                    b.Property<int>("PropertyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PropertyID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalUnits")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PropertyID");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.RenewalModel", b =>
                {
                    b.Property<int>("RenewalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenewalID"));

                    b.Property<int?>("ContractID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProposedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProposedValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RenewalID");

                    b.HasIndex("ContractID");

                    b.ToTable("Renewals");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.RevenueReportModel", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Metrics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportID");

                    b.ToTable("RevenueReports");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.SiteVisitModel", b =>
                {
                    b.Property<int>("VisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitID"));

                    b.Property<int?>("AgentID")
                        .HasColumnType("int");

                    b.Property<int?>("LeadID")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VisitID");

                    b.HasIndex("AgentID");

                    b.HasIndex("LeadID");

                    b.ToTable("SiteVisits");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.UnitModel", b =>
                {
                    b.Property<int>("UnitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitID"));

                    b.Property<double>("AreaSqFt")
                        .HasColumnType("float");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BedroomCount")
                        .HasColumnType("int");

                    b.Property<int>("PropertyID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnitNumber")
                        .HasColumnType("int");

                    b.HasKey("UnitID");

                    b.HasIndex("PropertyID");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.UserModel", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.VendorAssignmentModel", b =>
                {
                    b.Property<int>("AssignmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentID"));

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RequestID")
                        .HasColumnType("int");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentID");

                    b.HasIndex("RequestID");

                    b.ToTable("VendorAssignments");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.AmenityModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.PropertyModel", "PropertyModel")
                        .WithMany("Amenities")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.ContractModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.DealModel", "DealModel")
                        .WithMany()
                        .HasForeignKey("DealID");

                    b.Navigation("DealModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.DealModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.LeadModel", "LeadModel")
                        .WithMany("Deals")
                        .HasForeignKey("LeadID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropManageX.Models.Entities.UnitModel", "UnitModel")
                        .WithMany("Deals")
                        .HasForeignKey("UnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeadModel");

                    b.Navigation("UnitModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.InvoiceModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.ContractModel", "ContractModel")
                        .WithMany("Invoices")
                        .HasForeignKey("ContractID");

                    b.Navigation("ContractModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.LeadModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.PropertyModel", "PropertyModel")
                        .WithMany("Leads")
                        .HasForeignKey("PropertyID");

                    b.Navigation("PropertyModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.MaintenanceRequestModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.UserModel", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID");

                    b.HasOne("PropManageX.Models.Entities.UnitModel", "UnitModel")
                        .WithMany()
                        .HasForeignKey("UnitID");

                    b.Navigation("Tenant");

                    b.Navigation("UnitModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.NotificationModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.UserModel", "UserModel")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID");

                    b.Navigation("UserModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.RenewalModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.ContractModel", "ContractModel")
                        .WithMany()
                        .HasForeignKey("ContractID");

                    b.Navigation("ContractModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.SiteVisitModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.UserModel", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentID");

                    b.HasOne("PropManageX.Models.Entities.LeadModel", "LeadModel")
                        .WithMany("SiteVisits")
                        .HasForeignKey("LeadID");

                    b.Navigation("Agent");

                    b.Navigation("LeadModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.UnitModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.PropertyModel", "PropertyModel")
                        .WithMany("Units")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PropertyModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.VendorAssignmentModel", b =>
                {
                    b.HasOne("PropManageX.Models.Entities.MaintenanceRequestModel", "MaintenanceRequestModel")
                        .WithMany("VendorAssignments")
                        .HasForeignKey("RequestID");

                    b.Navigation("MaintenanceRequestModel");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.ContractModel", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.LeadModel", b =>
                {
                    b.Navigation("Deals");

                    b.Navigation("SiteVisits");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.MaintenanceRequestModel", b =>
                {
                    b.Navigation("VendorAssignments");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.PropertyModel", b =>
                {
                    b.Navigation("Amenities");

                    b.Navigation("Leads");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.UnitModel", b =>
                {
                    b.Navigation("Deals");
                });

            modelBuilder.Entity("PropManageX.Models.Entities.UserModel", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
